### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cenuno** [DS4PS/cpp-528-spr-2020#6]
Confirming that I receive email notification

**Comment by cenuno** [comment]
@cenuno do you get this email

**Comment by cenuno** [comment]
@cenuno once more for good measure

**Comment by lecy** [comment]
Did it work?

**Comment by cenuno** [comment]
Yes, thank goodness 👍

**Comment by lecy** [comment]
One more FYI, for questions on labs or coursework you can leave the issue open after answering so that all students have access to the same information (even though it feels good to close an issue!).

I will only close an issue if it is logistical, like fixing a broken link.

**Comment by cenuno** [comment]
That makes sense. I'll close this one and reopen the others. Thanks again!

**Comment by lecy** [comment]
Thank you!
